/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.laboratory.gui;

import java.awt.Toolkit;

/**
 *
 * @author sakshi
 */
public class Menu extends javax.swing.JFrame {
    private int roleId;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setLocationRelativeTo(null);
    }
    
    public Menu(int roleId) {
        this.roleId = roleId;
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        setLocationRelativeTo(null);
    
        if (roleId != 1) {
            mnuAccessibility.setEnabled(false);
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        mnuExit = new javax.swing.JMenu();
        mnuItemLogout = new javax.swing.JMenuItem();
        mnuAccessibility = new javax.swing.JMenu();
        mnuItemRole = new javax.swing.JMenuItem();
        mnuItemRegistration = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        mnuPatientDetails = new javax.swing.JMenu();
        mnuItemPatients = new javax.swing.JMenuItem();
        mnuTestList = new javax.swing.JMenu();
        mnuItemHematology = new javax.swing.JMenuItem();
        mnuBiochemistry = new javax.swing.JMenuItem();
        mnuItemCBC = new javax.swing.JMenuItem();
        mnuItemWBC = new javax.swing.JMenuItem();
        mnuItemUrinalysis = new javax.swing.JMenuItem();
        mnuTestReports = new javax.swing.JMenu();
        mnuItemHematologyReport = new javax.swing.JMenuItem();
        mnuItemBiochemistryReport = new javax.swing.JMenuItem();
        mnuItemCBCReport = new javax.swing.JMenuItem();
        mnuItemWBCReport = new javax.swing.JMenuItem();
        mnuItemUrinalysisReport = new javax.swing.JMenuItem();
        mnuTestAllotment = new javax.swing.JMenu();
        mnuItemHematologyAllotment = new javax.swing.JMenuItem();
        mnuItemBiochemistryAllotment = new javax.swing.JMenuItem();
        mnuItemCBCAllotment = new javax.swing.JMenuItem();
        mnuItemWBCAllotment = new javax.swing.JMenuItem();
        mnuItemUrinalysisAllotment = new javax.swing.JMenuItem();
        mnuFinalReport = new javax.swing.JMenu();
        mnuItemFinalPatientReport = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mnuExit.setText("Exit");

        mnuItemLogout.setText("Logout");
        mnuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemLogoutActionPerformed(evt);
            }
        });
        mnuExit.add(mnuItemLogout);

        menuBar.add(mnuExit);

        mnuAccessibility.setText("Admin's Accessibility");

        mnuItemRole.setText("Assign Role");
        mnuItemRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRoleActionPerformed(evt);
            }
        });
        mnuAccessibility.add(mnuItemRole);

        mnuItemRegistration.setText("Registration");
        mnuItemRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemRegistrationActionPerformed(evt);
            }
        });
        mnuAccessibility.add(mnuItemRegistration);

        copyMenuItem.setText("Update User");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        mnuAccessibility.add(copyMenuItem);

        menuBar.add(mnuAccessibility);

        mnuPatientDetails.setText("Patient Details");

        mnuItemPatients.setText("Add/Update Patients");
        mnuItemPatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemPatientsActionPerformed(evt);
            }
        });
        mnuPatientDetails.add(mnuItemPatients);

        menuBar.add(mnuPatientDetails);

        mnuTestList.setText("Test List");

        mnuItemHematology.setText("Hematology Test");
        mnuItemHematology.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemHematologyActionPerformed(evt);
            }
        });
        mnuTestList.add(mnuItemHematology);

        mnuBiochemistry.setText("Biochemistry Test");
        mnuBiochemistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBiochemistryActionPerformed(evt);
            }
        });
        mnuTestList.add(mnuBiochemistry);

        mnuItemCBC.setText("Complete Blood Count(CBC) Test");
        mnuItemCBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCBCActionPerformed(evt);
            }
        });
        mnuTestList.add(mnuItemCBC);

        mnuItemWBC.setText("WBC Differential Count Test");
        mnuItemWBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemWBCActionPerformed(evt);
            }
        });
        mnuTestList.add(mnuItemWBC);

        mnuItemUrinalysis.setText("Urinalysis Test");
        mnuItemUrinalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUrinalysisActionPerformed(evt);
            }
        });
        mnuTestList.add(mnuItemUrinalysis);

        menuBar.add(mnuTestList);

        mnuTestReports.setText("Test Reports");

        mnuItemHematologyReport.setText("Hematology Test Report");
        mnuItemHematologyReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemHematologyReportActionPerformed(evt);
            }
        });
        mnuTestReports.add(mnuItemHematologyReport);

        mnuItemBiochemistryReport.setText("Biochemistry Test Report");
        mnuItemBiochemistryReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBiochemistryReportActionPerformed(evt);
            }
        });
        mnuTestReports.add(mnuItemBiochemistryReport);

        mnuItemCBCReport.setText("Complete Blood Count(CBC) Test Report");
        mnuItemCBCReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCBCReportActionPerformed(evt);
            }
        });
        mnuTestReports.add(mnuItemCBCReport);

        mnuItemWBCReport.setText("WBC Differential Count Test Report");
        mnuItemWBCReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemWBCReportActionPerformed(evt);
            }
        });
        mnuTestReports.add(mnuItemWBCReport);

        mnuItemUrinalysisReport.setText("Urinalysis Test Report");
        mnuItemUrinalysisReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUrinalysisReportActionPerformed(evt);
            }
        });
        mnuTestReports.add(mnuItemUrinalysisReport);

        menuBar.add(mnuTestReports);

        mnuTestAllotment.setText("Test Allotment");

        mnuItemHematologyAllotment.setText("Hematology Test Alloted");
        mnuItemHematologyAllotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemHematologyAllotmentActionPerformed(evt);
            }
        });
        mnuTestAllotment.add(mnuItemHematologyAllotment);

        mnuItemBiochemistryAllotment.setText("Biochemistry Test Alloted");
        mnuItemBiochemistryAllotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemBiochemistryAllotmentActionPerformed(evt);
            }
        });
        mnuTestAllotment.add(mnuItemBiochemistryAllotment);

        mnuItemCBCAllotment.setText("Complete Blood Count(CBC) Test Alloted");
        mnuItemCBCAllotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemCBCAllotmentActionPerformed(evt);
            }
        });
        mnuTestAllotment.add(mnuItemCBCAllotment);

        mnuItemWBCAllotment.setText("WBC Differential Count Test Alloted");
        mnuItemWBCAllotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemWBCAllotmentActionPerformed(evt);
            }
        });
        mnuTestAllotment.add(mnuItemWBCAllotment);

        mnuItemUrinalysisAllotment.setText("Urinalysis Test Alloted");
        mnuItemUrinalysisAllotment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemUrinalysisAllotmentActionPerformed(evt);
            }
        });
        mnuTestAllotment.add(mnuItemUrinalysisAllotment);

        menuBar.add(mnuTestAllotment);

        mnuFinalReport.setText("Final Report");

        mnuItemFinalPatientReport.setText("Final Patient's Test Report and PDF");
        mnuItemFinalPatientReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuItemFinalPatientReportActionPerformed(evt);
            }
        });
        mnuFinalReport.add(mnuItemFinalPatientReport);

        menuBar.add(mnuFinalReport);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemLogoutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_mnuItemLogoutActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        UpdateUser update=new UpdateUser();
        desktopPane.add(update);
        update.setVisible(true);
    }//GEN-LAST:event_copyMenuItemActionPerformed

    private void mnuItemPatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemPatientsActionPerformed
        // TODO add your handling code here:
        PatientFrame patient=new PatientFrame();
        desktopPane.add(patient);
        patient.setVisible(true);
    }//GEN-LAST:event_mnuItemPatientsActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void mnuItemRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRoleActionPerformed
        // TODO add your handling code here:
        RoleFrame role=new RoleFrame();
        desktopPane.add(role);
        role.setVisible(true);
    }//GEN-LAST:event_mnuItemRoleActionPerformed

    private void mnuItemRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemRegistrationActionPerformed
        // TODO add your handling code here:
        RegisterFrame register=new RegisterFrame();
        desktopPane.add(register);
        register.setVisible(true);
    }//GEN-LAST:event_mnuItemRegistrationActionPerformed

    private void mnuItemHematologyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemHematologyActionPerformed
        // TODO add your handling code here:
        HematologyFrame hematology=new HematologyFrame();
        desktopPane.add(hematology);
        hematology.setVisible(true);
    }//GEN-LAST:event_mnuItemHematologyActionPerformed

    private void mnuBiochemistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBiochemistryActionPerformed
        // TODO add your handling code here:
        BiochemistryFrame biochemistry=new BiochemistryFrame();
        desktopPane.add(biochemistry);
        biochemistry.setVisible(true);
    }//GEN-LAST:event_mnuBiochemistryActionPerformed

    private void mnuItemUrinalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUrinalysisActionPerformed
        // TODO add your handling code here:
        UrinalysisFrame urinalysis=new UrinalysisFrame();
        desktopPane.add(urinalysis);
        urinalysis.setVisible(true);
    }//GEN-LAST:event_mnuItemUrinalysisActionPerformed

    private void mnuItemCBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCBCActionPerformed
        // TODO add your handling code here:
        CompleteBloodCountFrame completebloodcount=new CompleteBloodCountFrame();
        desktopPane.add(completebloodcount);
        completebloodcount.setVisible(true);
    }//GEN-LAST:event_mnuItemCBCActionPerformed

    private void mnuItemWBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemWBCActionPerformed
        // TODO add your handling code here:
        WBCDifferentialCountFrame wbcdifferentialcount=new WBCDifferentialCountFrame();
        desktopPane.add(wbcdifferentialcount);
        wbcdifferentialcount.setVisible(true);
    }//GEN-LAST:event_mnuItemWBCActionPerformed

    private void mnuItemHematologyReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemHematologyReportActionPerformed
        // TODO add your handling code here:
        HematologyReport hematologyreport=new HematologyReport();
        desktopPane.add(hematologyreport);
        hematologyreport.setVisible(true);
        
    }//GEN-LAST:event_mnuItemHematologyReportActionPerformed

    private void mnuItemBiochemistryReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBiochemistryReportActionPerformed
        // TODO add your handling code here:
        BiochemistryReport biochemistryreport = new BiochemistryReport();
        desktopPane.add(biochemistryreport);
        biochemistryreport.setVisible(true);
    }//GEN-LAST:event_mnuItemBiochemistryReportActionPerformed

    private void mnuItemHematologyAllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemHematologyAllotmentActionPerformed
        // TODO add your handling code here:
        HematologyTestAllotmentFrame hematologyallotment=new HematologyTestAllotmentFrame();
        desktopPane.add(hematologyallotment);
        hematologyallotment.setVisible(true);
    }//GEN-LAST:event_mnuItemHematologyAllotmentActionPerformed

    private void mnuItemBiochemistryAllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemBiochemistryAllotmentActionPerformed
        // TODO add your handling code here:
        BiochemistryTestAllotmentFrame biochemistryallotment=new BiochemistryTestAllotmentFrame();
        desktopPane.add(biochemistryallotment);
        biochemistryallotment.setVisible(true);
    }//GEN-LAST:event_mnuItemBiochemistryAllotmentActionPerformed

    private void mnuItemCBCAllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCBCAllotmentActionPerformed
        // TODO add your handling code here:
        CBCTestAllotmentFrame cbcallotment = new CBCTestAllotmentFrame();
        desktopPane.add(cbcallotment);
        cbcallotment.setVisible(true);
    }//GEN-LAST:event_mnuItemCBCAllotmentActionPerformed

    private void mnuItemWBCAllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemWBCAllotmentActionPerformed
        // TODO add your handling code here:
        WBCDifferentialCountTestAllotmentFrame wbcdifferentialcountallotment = new WBCDifferentialCountTestAllotmentFrame();
        desktopPane.add(wbcdifferentialcountallotment);
        wbcdifferentialcountallotment.setVisible(true);
    }//GEN-LAST:event_mnuItemWBCAllotmentActionPerformed

    private void mnuItemUrinalysisAllotmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUrinalysisAllotmentActionPerformed
        // TODO add your handling code here:
        UrinalysisTestAllotmentFrame urinalysisallotment = new UrinalysisTestAllotmentFrame();
        desktopPane.add(urinalysisallotment);
        urinalysisallotment.setVisible(true);
    }//GEN-LAST:event_mnuItemUrinalysisAllotmentActionPerformed

    private void mnuItemCBCReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemCBCReportActionPerformed
        // TODO add your handling code here:
        CompleteBloodCountReport completebloodcountreport = new CompleteBloodCountReport();
        desktopPane.add(completebloodcountreport);
        completebloodcountreport.setVisible(true);
    }//GEN-LAST:event_mnuItemCBCReportActionPerformed

    private void mnuItemWBCReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemWBCReportActionPerformed
        // TODO add your handling code here:
        WBCDifferentialCountReport wbcdifferentialcountreport = new WBCDifferentialCountReport();
        desktopPane.add(wbcdifferentialcountreport);
        wbcdifferentialcountreport.setVisible(true);
    }//GEN-LAST:event_mnuItemWBCReportActionPerformed

    private void mnuItemUrinalysisReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemUrinalysisReportActionPerformed
        // TODO add your handling code here:
        UrinalysisReport urinalysisreport = new UrinalysisReport();
        desktopPane.add(urinalysisreport);
        urinalysisreport.setVisible(true);
    }//GEN-LAST:event_mnuItemUrinalysisReportActionPerformed

    private void mnuItemFinalPatientReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuItemFinalPatientReportActionPerformed
        // TODO add your handling code here:
        FinalTestReport finaltestreport = new FinalTestReport();
        desktopPane.add(finaltestreport);
        finaltestreport.setVisible(true);
    }//GEN-LAST:event_mnuItemFinalPatientReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnuAccessibility;
    private javax.swing.JMenuItem mnuBiochemistry;
    private javax.swing.JMenu mnuExit;
    private javax.swing.JMenu mnuFinalReport;
    private javax.swing.JMenuItem mnuItemBiochemistryAllotment;
    private javax.swing.JMenuItem mnuItemBiochemistryReport;
    private javax.swing.JMenuItem mnuItemCBC;
    private javax.swing.JMenuItem mnuItemCBCAllotment;
    private javax.swing.JMenuItem mnuItemCBCReport;
    private javax.swing.JMenuItem mnuItemFinalPatientReport;
    private javax.swing.JMenuItem mnuItemHematology;
    private javax.swing.JMenuItem mnuItemHematologyAllotment;
    private javax.swing.JMenuItem mnuItemHematologyReport;
    private javax.swing.JMenuItem mnuItemLogout;
    private javax.swing.JMenuItem mnuItemPatients;
    private javax.swing.JMenuItem mnuItemRegistration;
    private javax.swing.JMenuItem mnuItemRole;
    private javax.swing.JMenuItem mnuItemUrinalysis;
    private javax.swing.JMenuItem mnuItemUrinalysisAllotment;
    private javax.swing.JMenuItem mnuItemUrinalysisReport;
    private javax.swing.JMenuItem mnuItemWBC;
    private javax.swing.JMenuItem mnuItemWBCAllotment;
    private javax.swing.JMenuItem mnuItemWBCReport;
    private javax.swing.JMenu mnuPatientDetails;
    private javax.swing.JMenu mnuTestAllotment;
    private javax.swing.JMenu mnuTestList;
    private javax.swing.JMenu mnuTestReports;
    // End of variables declaration//GEN-END:variables

}
